### ISSUE TITLE
Connect DAO and Vision

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#68]
Currently, we have separate actions to create a vision and organization. 

This should be a single action. When a new organization is created, the vision is a mandatory field that allows the founder to upload a vision document. Vision should be a mandatory field of the organization struct. 

- [x] Update the DAO pallet to include this change. 
- [x] We need separate Vision Struct that holds metadata information about the vision. Vision is still a field in DAO struct as well.
- [x] Add/update tests

**Comment by f-gate** [comment]
- [x] Remove add/remove vision extrinsics
- [x] Change signing capabilities so it signs the vision of an organisation as opposed to the vision hash
- [x] Create organisation - uses vision struct instead of u8
- [x] Update organisation - ^^
- [x] Query the Vision storage type, why are we storing this mapping? and why cant 2 organisations have the same vision?
- [x] Change documentation.
- [x] Update tests
- [x] Update benchmarks

**Comment by f-gate** [comment]
need to talk about Vision storage and multiple organisations with same vision

**Comment by stojanov-igor** [comment]
> need to talk about Vision storage and multiple organisations with same vision

What is the question about Vision storage? Ideally, there should not be organizations with the same vision.
